// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum BluetoothLowEnergyStateArgs {
  unknown,
  unsupported,
  disabled,
  off,
  on,
}

enum AdvertisementTypeArgs {
  connectableUndirected,
  connectableDirected,
  scannableUndirected,
  nonConnectableUndirected,
  scanResponse,
  extended,
}

enum ConnectionStateArgs {
  disconnected,
  connected,
}

enum GATTCharacteristicPropertyArgs {
  read,
  write,
  writeWithoutResponse,
  notify,
  indicate,
}

enum GATTCharacteristicWriteTypeArgs {
  withResponse,
  withoutResponse,
}

enum GATTCharacteristicNotifyStateArgs {
  none,
  notify,
  indicate,
}

enum GATTProtectionLevelArgs {
  plain,
  authenticationRequired,
  entryptionRequired,
  encryptionAndAuthenticationRequired,
}

enum GATTProtocolErrorArgs {
  invalidHandle,
  readNotPermitted,
  writeNotPermitted,
  invalidPDU,
  insufficientAuthentication,
  requestNotSupported,
  invalidOffset,
  insufficientAuthorization,
  prepareQueueFull,
  attributeNotFound,
  attributeNotLong,
  insufficientEncryptionKeySize,
  invalidAttributeValueLength,
  unlikelyError,
  insufficientEncryption,
  unsupportedGroupType,
  insufficientResources,
}

enum CacheModeArgs {
  cached,
  uncached,
}

class ManufacturerSpecificDataArgs {
  ManufacturerSpecificDataArgs({
    required this.idArgs,
    required this.dataArgs,
  });

  int idArgs;

  Uint8List dataArgs;

  List<Object?> _toList() {
    return <Object?>[
      idArgs,
      dataArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static ManufacturerSpecificDataArgs decode(Object result) {
    result as List<Object?>;
    return ManufacturerSpecificDataArgs(
      idArgs: result[0]! as int,
      dataArgs: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ManufacturerSpecificDataArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(idArgs, other.idArgs) && _deepEquals(dataArgs, other.dataArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AdvertisementArgs {
  AdvertisementArgs({
    this.nameArgs,
    required this.serviceUUIDsArgs,
    required this.serviceDataArgs,
    required this.manufacturerSpecificDataArgs,
  });

  String? nameArgs;

  List<String> serviceUUIDsArgs;

  Map<String, Uint8List> serviceDataArgs;

  List<ManufacturerSpecificDataArgs> manufacturerSpecificDataArgs;

  List<Object?> _toList() {
    return <Object?>[
      nameArgs,
      serviceUUIDsArgs,
      serviceDataArgs,
      manufacturerSpecificDataArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AdvertisementArgs decode(Object result) {
    result as List<Object?>;
    return AdvertisementArgs(
      nameArgs: result[0] as String?,
      serviceUUIDsArgs: (result[1]! as List<Object?>).cast<String>(),
      serviceDataArgs: (result[2]! as Map<Object?, Object?>).cast<String, Uint8List>(),
      manufacturerSpecificDataArgs: (result[3]! as List<Object?>).cast<ManufacturerSpecificDataArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AdvertisementArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(nameArgs, other.nameArgs) && _deepEquals(serviceUUIDsArgs, other.serviceUUIDsArgs) && _deepEquals(serviceDataArgs, other.serviceDataArgs) && _deepEquals(manufacturerSpecificDataArgs, other.manufacturerSpecificDataArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CentralArgs {
  CentralArgs({
    required this.addressArgs,
  });

  int addressArgs;

  List<Object?> _toList() {
    return <Object?>[
      addressArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static CentralArgs decode(Object result) {
    result as List<Object?>;
    return CentralArgs(
      addressArgs: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CentralArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(addressArgs, other.addressArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PeripheralArgs {
  PeripheralArgs({
    required this.addressArgs,
  });

  int addressArgs;

  List<Object?> _toList() {
    return <Object?>[
      addressArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static PeripheralArgs decode(Object result) {
    result as List<Object?>;
    return PeripheralArgs(
      addressArgs: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PeripheralArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(addressArgs, other.addressArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GATTDescriptorArgs {
  GATTDescriptorArgs({
    required this.handleArgs,
    required this.uuidArgs,
  });

  int handleArgs;

  String uuidArgs;

  List<Object?> _toList() {
    return <Object?>[
      handleArgs,
      uuidArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTDescriptorArgs decode(Object result) {
    result as List<Object?>;
    return GATTDescriptorArgs(
      handleArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTDescriptorArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(handleArgs, other.handleArgs) && _deepEquals(uuidArgs, other.uuidArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GATTCharacteristicArgs {
  GATTCharacteristicArgs({
    required this.handleArgs,
    required this.uuidArgs,
    required this.propertyNumbersArgs,
    required this.descriptorsArgs,
  });

  int handleArgs;

  String uuidArgs;

  List<int> propertyNumbersArgs;

  List<GATTDescriptorArgs> descriptorsArgs;

  List<Object?> _toList() {
    return <Object?>[
      handleArgs,
      uuidArgs,
      propertyNumbersArgs,
      descriptorsArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTCharacteristicArgs decode(Object result) {
    result as List<Object?>;
    return GATTCharacteristicArgs(
      handleArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      propertyNumbersArgs: (result[2]! as List<Object?>).cast<int>(),
      descriptorsArgs: (result[3]! as List<Object?>).cast<GATTDescriptorArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTCharacteristicArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(handleArgs, other.handleArgs) && _deepEquals(uuidArgs, other.uuidArgs) && _deepEquals(propertyNumbersArgs, other.propertyNumbersArgs) && _deepEquals(descriptorsArgs, other.descriptorsArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GATTServiceArgs {
  GATTServiceArgs({
    required this.handleArgs,
    required this.uuidArgs,
    required this.isPrimaryArgs,
    required this.includedServicesArgs,
    required this.characteristicsArgs,
  });

  int handleArgs;

  String uuidArgs;

  bool isPrimaryArgs;

  List<GATTServiceArgs> includedServicesArgs;

  List<GATTCharacteristicArgs> characteristicsArgs;

  List<Object?> _toList() {
    return <Object?>[
      handleArgs,
      uuidArgs,
      isPrimaryArgs,
      includedServicesArgs,
      characteristicsArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTServiceArgs decode(Object result) {
    result as List<Object?>;
    return GATTServiceArgs(
      handleArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      isPrimaryArgs: result[2]! as bool,
      includedServicesArgs: (result[3]! as List<Object?>).cast<GATTServiceArgs>(),
      characteristicsArgs: (result[4]! as List<Object?>).cast<GATTCharacteristicArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTServiceArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(handleArgs, other.handleArgs) && _deepEquals(uuidArgs, other.uuidArgs) && _deepEquals(isPrimaryArgs, other.isPrimaryArgs) && _deepEquals(includedServicesArgs, other.includedServicesArgs) && _deepEquals(characteristicsArgs, other.characteristicsArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MutableGATTDescriptorArgs {
  MutableGATTDescriptorArgs({
    required this.hashCodeArgs,
    required this.uuidArgs,
    this.valueArgs,
    this.readProtectionLevelArgs,
    this.writeProtectionLevelArgs,
  });

  int hashCodeArgs;

  String uuidArgs;

  Uint8List? valueArgs;

  GATTProtectionLevelArgs? readProtectionLevelArgs;

  GATTProtectionLevelArgs? writeProtectionLevelArgs;

  List<Object?> _toList() {
    return <Object?>[
      hashCodeArgs,
      uuidArgs,
      valueArgs,
      readProtectionLevelArgs,
      writeProtectionLevelArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableGATTDescriptorArgs decode(Object result) {
    result as List<Object?>;
    return MutableGATTDescriptorArgs(
      hashCodeArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      valueArgs: result[2] as Uint8List?,
      readProtectionLevelArgs: result[3] as GATTProtectionLevelArgs?,
      writeProtectionLevelArgs: result[4] as GATTProtectionLevelArgs?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableGATTDescriptorArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hashCodeArgs, other.hashCodeArgs) && _deepEquals(uuidArgs, other.uuidArgs) && _deepEquals(valueArgs, other.valueArgs) && _deepEquals(readProtectionLevelArgs, other.readProtectionLevelArgs) && _deepEquals(writeProtectionLevelArgs, other.writeProtectionLevelArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MutableGATTCharacteristicArgs {
  MutableGATTCharacteristicArgs({
    required this.hashCodeArgs,
    required this.uuidArgs,
    this.valueArgs,
    required this.propertyNumbersArgs,
    this.readProtectionLevelArgs,
    this.writeProtectionLevelArgs,
    required this.descriptorsArgs,
  });

  int hashCodeArgs;

  String uuidArgs;

  Uint8List? valueArgs;

  List<int> propertyNumbersArgs;

  GATTProtectionLevelArgs? readProtectionLevelArgs;

  GATTProtectionLevelArgs? writeProtectionLevelArgs;

  List<MutableGATTDescriptorArgs> descriptorsArgs;

  List<Object?> _toList() {
    return <Object?>[
      hashCodeArgs,
      uuidArgs,
      valueArgs,
      propertyNumbersArgs,
      readProtectionLevelArgs,
      writeProtectionLevelArgs,
      descriptorsArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableGATTCharacteristicArgs decode(Object result) {
    result as List<Object?>;
    return MutableGATTCharacteristicArgs(
      hashCodeArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      valueArgs: result[2] as Uint8List?,
      propertyNumbersArgs: (result[3]! as List<Object?>).cast<int>(),
      readProtectionLevelArgs: result[4] as GATTProtectionLevelArgs?,
      writeProtectionLevelArgs: result[5] as GATTProtectionLevelArgs?,
      descriptorsArgs: (result[6]! as List<Object?>).cast<MutableGATTDescriptorArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableGATTCharacteristicArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hashCodeArgs, other.hashCodeArgs) && _deepEquals(uuidArgs, other.uuidArgs) && _deepEquals(valueArgs, other.valueArgs) && _deepEquals(propertyNumbersArgs, other.propertyNumbersArgs) && _deepEquals(readProtectionLevelArgs, other.readProtectionLevelArgs) && _deepEquals(writeProtectionLevelArgs, other.writeProtectionLevelArgs) && _deepEquals(descriptorsArgs, other.descriptorsArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MutableGATTServiceArgs {
  MutableGATTServiceArgs({
    required this.hashCodeArgs,
    required this.uuidArgs,
    required this.isPrimaryArgs,
    required this.includedServicesArgs,
    required this.characteristicsArgs,
  });

  int hashCodeArgs;

  String uuidArgs;

  bool isPrimaryArgs;

  List<MutableGATTServiceArgs> includedServicesArgs;

  List<MutableGATTCharacteristicArgs> characteristicsArgs;

  List<Object?> _toList() {
    return <Object?>[
      hashCodeArgs,
      uuidArgs,
      isPrimaryArgs,
      includedServicesArgs,
      characteristicsArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableGATTServiceArgs decode(Object result) {
    result as List<Object?>;
    return MutableGATTServiceArgs(
      hashCodeArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      isPrimaryArgs: result[2]! as bool,
      includedServicesArgs: (result[3]! as List<Object?>).cast<MutableGATTServiceArgs>(),
      characteristicsArgs: (result[4]! as List<Object?>).cast<MutableGATTCharacteristicArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableGATTServiceArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hashCodeArgs, other.hashCodeArgs) && _deepEquals(uuidArgs, other.uuidArgs) && _deepEquals(isPrimaryArgs, other.isPrimaryArgs) && _deepEquals(includedServicesArgs, other.includedServicesArgs) && _deepEquals(characteristicsArgs, other.characteristicsArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GATTReadRequestArgs {
  GATTReadRequestArgs({
    required this.idArgs,
    required this.offsetArgs,
    required this.lengthArgs,
  });

  int idArgs;

  int offsetArgs;

  int lengthArgs;

  List<Object?> _toList() {
    return <Object?>[
      idArgs,
      offsetArgs,
      lengthArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTReadRequestArgs decode(Object result) {
    result as List<Object?>;
    return GATTReadRequestArgs(
      idArgs: result[0]! as int,
      offsetArgs: result[1]! as int,
      lengthArgs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTReadRequestArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(idArgs, other.idArgs) && _deepEquals(offsetArgs, other.offsetArgs) && _deepEquals(lengthArgs, other.lengthArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GATTWriteRequestArgs {
  GATTWriteRequestArgs({
    required this.idArgs,
    required this.offsetArgs,
    required this.valueArgs,
    required this.typeArgs,
  });

  int idArgs;

  int offsetArgs;

  Uint8List valueArgs;

  GATTCharacteristicWriteTypeArgs typeArgs;

  List<Object?> _toList() {
    return <Object?>[
      idArgs,
      offsetArgs,
      valueArgs,
      typeArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTWriteRequestArgs decode(Object result) {
    result as List<Object?>;
    return GATTWriteRequestArgs(
      idArgs: result[0]! as int,
      offsetArgs: result[1]! as int,
      valueArgs: result[2]! as Uint8List,
      typeArgs: result[3]! as GATTCharacteristicWriteTypeArgs,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTWriteRequestArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(idArgs, other.idArgs) && _deepEquals(offsetArgs, other.offsetArgs) && _deepEquals(valueArgs, other.valueArgs) && _deepEquals(typeArgs, other.typeArgs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BluetoothLowEnergyStateArgs) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AdvertisementTypeArgs) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ConnectionStateArgs) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is GATTCharacteristicPropertyArgs) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is GATTCharacteristicWriteTypeArgs) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is GATTCharacteristicNotifyStateArgs) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is GATTProtectionLevelArgs) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is GATTProtocolErrorArgs) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is CacheModeArgs) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is ManufacturerSpecificDataArgs) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is AdvertisementArgs) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is CentralArgs) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is PeripheralArgs) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is GATTDescriptorArgs) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is GATTCharacteristicArgs) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is GATTServiceArgs) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is MutableGATTDescriptorArgs) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is MutableGATTCharacteristicArgs) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is MutableGATTServiceArgs) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is GATTReadRequestArgs) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is GATTWriteRequestArgs) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BluetoothLowEnergyStateArgs.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AdvertisementTypeArgs.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConnectionStateArgs.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : GATTCharacteristicPropertyArgs.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : GATTCharacteristicWriteTypeArgs.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : GATTCharacteristicNotifyStateArgs.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : GATTProtectionLevelArgs.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : GATTProtocolErrorArgs.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : CacheModeArgs.values[value];
      case 138:
        return ManufacturerSpecificDataArgs.decode(readValue(buffer)!);
      case 139:
        return AdvertisementArgs.decode(readValue(buffer)!);
      case 140:
        return CentralArgs.decode(readValue(buffer)!);
      case 141:
        return PeripheralArgs.decode(readValue(buffer)!);
      case 142:
        return GATTDescriptorArgs.decode(readValue(buffer)!);
      case 143:
        return GATTCharacteristicArgs.decode(readValue(buffer)!);
      case 144:
        return GATTServiceArgs.decode(readValue(buffer)!);
      case 145:
        return MutableGATTDescriptorArgs.decode(readValue(buffer)!);
      case 146:
        return MutableGATTCharacteristicArgs.decode(readValue(buffer)!);
      case 147:
        return MutableGATTServiceArgs.decode(readValue(buffer)!);
      case 148:
        return GATTReadRequestArgs.decode(readValue(buffer)!);
      case 149:
        return GATTWriteRequestArgs.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CentralManagerHostApi {
  /// Constructor for [CentralManagerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CentralManagerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<BluetoothLowEnergyStateArgs> getState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BluetoothLowEnergyStateArgs;
  }

  Future<void> startDiscovery(List<String> serviceUUIDsArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.startDiscovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUUIDsArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopDiscovery() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.stopDiscovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> connect(int addressArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disconnect(int addressArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> pair(int addressArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.pair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Returns true only when Windows had a pairing record and removed it.
  Future<bool> unpairIfPaired(int addressArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.unpairIfPaired$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<Uint8List> connectRfcomm(int addressArgs, String serviceUuidArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.connectRfcomm$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, serviceUuidArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<void> disconnectRfcomm(int addressArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.disconnectRfcomm$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> rfcommWrite(int addressArgs, Uint8List dataArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.rfcommWrite$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, dataArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> getMTU(int addressArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getMTU$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<List<GATTServiceArgs>> getServices(int addressArgs, CacheModeArgs modeArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, modeArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<GATTServiceArgs>();
  }

  Future<List<GATTServiceArgs>> getIncludedServices(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getIncludedServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<GATTServiceArgs>();
  }

  Future<List<GATTCharacteristicArgs>> getCharacteristics(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getCharacteristics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<GATTCharacteristicArgs>();
  }

  Future<List<GATTDescriptorArgs>> getDescriptors(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getDescriptors$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<GATTDescriptorArgs>();
  }

  Future<Uint8List> readCharacteristic(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.readCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<void> writeCharacteristic(int addressArgs, int handleArgs, Uint8List valueArgs, GATTCharacteristicWriteTypeArgs typeArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.writeCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, valueArgs, typeArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setCharacteristicNotifyState(int addressArgs, int handleArgs, GATTCharacteristicNotifyStateArgs stateArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.setCharacteristicNotifyState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, stateArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<Uint8List> readDescriptor(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.readDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<void> writeDescriptor(int addressArgs, int handleArgs, Uint8List valueArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.writeDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, valueArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class CentralManagerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStateChanged(BluetoothLowEnergyStateArgs stateArgs);

  void onDiscovered(PeripheralArgs peripheralArgs, int rssiArgs, int timestampArgs, AdvertisementTypeArgs typeArgs, AdvertisementArgs advertisementArgs);

  void onConnectionStateChanged(PeripheralArgs peripheralArgs, ConnectionStateArgs stateArgs);

  void onMTUChanged(PeripheralArgs peripheralArgs, int mtuArgs);

  void onCharacteristicNotified(PeripheralArgs peripheralArgs, GATTCharacteristicArgs characteristicArgs, Uint8List valueArgs);

  void onRfcommData(int addressArgs, Uint8List dataArgs);

  static void setUp(CentralManagerFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final BluetoothLowEnergyStateArgs arg_stateArgs = args[0]! as BluetoothLowEnergyStateArgs;
          try {
            api.onStateChanged(arg_stateArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onDiscovered$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PeripheralArgs arg_peripheralArgs = args[0]! as PeripheralArgs;
          final int arg_rssiArgs = args[1]! as int;
          final int arg_timestampArgs = args[2]! as int;
          final AdvertisementTypeArgs arg_typeArgs = args[3]! as AdvertisementTypeArgs;
          final AdvertisementArgs arg_advertisementArgs = args[4]! as AdvertisementArgs;
          try {
            api.onDiscovered(arg_peripheralArgs, arg_rssiArgs, arg_timestampArgs, arg_typeArgs, arg_advertisementArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onConnectionStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PeripheralArgs arg_peripheralArgs = args[0]! as PeripheralArgs;
          final ConnectionStateArgs arg_stateArgs = args[1]! as ConnectionStateArgs;
          try {
            api.onConnectionStateChanged(arg_peripheralArgs, arg_stateArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onMTUChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PeripheralArgs arg_peripheralArgs = args[0]! as PeripheralArgs;
          final int arg_mtuArgs = args[1]! as int;
          try {
            api.onMTUChanged(arg_peripheralArgs, arg_mtuArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onCharacteristicNotified$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PeripheralArgs arg_peripheralArgs = args[0]! as PeripheralArgs;
          final GATTCharacteristicArgs arg_characteristicArgs = args[1]! as GATTCharacteristicArgs;
          final Uint8List arg_valueArgs = args[2]! as Uint8List;
          try {
            api.onCharacteristicNotified(arg_peripheralArgs, arg_characteristicArgs, arg_valueArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onRfcommData$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_addressArgs = args[0]! as int;
          final Uint8List arg_dataArgs = args[1]! as Uint8List;
          try {
            api.onRfcommData(arg_addressArgs, arg_dataArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class PeripheralManagerHostApi {
  /// Constructor for [PeripheralManagerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PeripheralManagerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<BluetoothLowEnergyStateArgs> getState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.getState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BluetoothLowEnergyStateArgs;
  }

  Future<void> addService(MutableGATTServiceArgs serviceArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.addService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> removeService(int hashCodeArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.removeService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[hashCodeArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startAdvertising(AdvertisementArgs advertisementArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.startAdvertising$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[advertisementArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopAdvertising() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.stopAdvertising$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> getMaxNotificationSize(int addressArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.getMaxNotificationSize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<void> respondReadRequestWithValue(int idArgs, Uint8List valueArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.respondReadRequestWithValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[idArgs, valueArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> respondReadRequestWithProtocolError(int idArgs, GATTProtocolErrorArgs errorArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.respondReadRequestWithProtocolError$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[idArgs, errorArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> respondWriteRequest(int idArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.respondWriteRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[idArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> respondWriteRequestWithProtocolError(int idArgs, GATTProtocolErrorArgs errorArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.respondWriteRequestWithProtocolError$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[idArgs, errorArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> notifyValue(int addressArgs, int hashCodeArgs, Uint8List valueArgs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.notifyValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, hashCodeArgs, valueArgs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class PeripheralManagerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStateChanged(BluetoothLowEnergyStateArgs stateArgs);

  void onMTUChanged(CentralArgs centralArgs, int mtuArgs);

  void onCharacteristicReadRequest(CentralArgs centralArgs, int hashCodeArgs, GATTReadRequestArgs requestArgs);

  void onCharacteristicWriteRequest(CentralArgs centralArgs, int hashCodeArgs, GATTWriteRequestArgs requestArgs);

  void onCharacteristicSubscribedClientsChanged(int hashCodeArgs, List<CentralArgs> centralsArgs);

  void onDescriptorReadRequest(CentralArgs centralArgs, int hashCodeArgs, GATTReadRequestArgs requestArgs);

  void onDescriptorWriteRequest(CentralArgs centralArgs, int hashCodeArgs, GATTWriteRequestArgs requestArgs);

  static void setUp(PeripheralManagerFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final BluetoothLowEnergyStateArgs arg_stateArgs = args[0]! as BluetoothLowEnergyStateArgs;
          try {
            api.onStateChanged(arg_stateArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onMTUChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CentralArgs arg_centralArgs = args[0]! as CentralArgs;
          final int arg_mtuArgs = args[1]! as int;
          try {
            api.onMTUChanged(arg_centralArgs, arg_mtuArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicReadRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CentralArgs arg_centralArgs = args[0]! as CentralArgs;
          final int arg_hashCodeArgs = args[1]! as int;
          final GATTReadRequestArgs arg_requestArgs = args[2]! as GATTReadRequestArgs;
          try {
            api.onCharacteristicReadRequest(arg_centralArgs, arg_hashCodeArgs, arg_requestArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicWriteRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CentralArgs arg_centralArgs = args[0]! as CentralArgs;
          final int arg_hashCodeArgs = args[1]! as int;
          final GATTWriteRequestArgs arg_requestArgs = args[2]! as GATTWriteRequestArgs;
          try {
            api.onCharacteristicWriteRequest(arg_centralArgs, arg_hashCodeArgs, arg_requestArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicSubscribedClientsChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_hashCodeArgs = args[0]! as int;
          final List<CentralArgs> arg_centralsArgs = (args[1]! as List<Object?>).cast<CentralArgs>();
          try {
            api.onCharacteristicSubscribedClientsChanged(arg_hashCodeArgs, arg_centralsArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorReadRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CentralArgs arg_centralArgs = args[0]! as CentralArgs;
          final int arg_hashCodeArgs = args[1]! as int;
          final GATTReadRequestArgs arg_requestArgs = args[2]! as GATTReadRequestArgs;
          try {
            api.onDescriptorReadRequest(arg_centralArgs, arg_hashCodeArgs, arg_requestArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorWriteRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CentralArgs arg_centralArgs = args[0]! as CentralArgs;
          final int arg_hashCodeArgs = args[1]! as int;
          final GATTWriteRequestArgs arg_requestArgs = args[2]! as GATTWriteRequestArgs;
          try {
            api.onDescriptorWriteRequest(arg_centralArgs, arg_hashCodeArgs, arg_requestArgs);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
